import React from'react';
import styles from './userDisplayList.module.css'
import { SongDetail } from '../trackDetail/songDetail';
import spotifyLogo from '../userListContainer/image/Spotify-Logo-Download-Free.png'; 

 const UsertDisplayContainer = React.memo((props)=>{

    //Variable 
    const listTitle = props.listTitle || 'New Playlist' ; 
    const {handlePlayListTitle, resetPlayListTitle, handleRemoveTrackFromStore , handleLoginService} = props.storeActions; 
    const {storeTrack}= props;

    //Iterate the saved playlist
    let savedPlayList; 

    if(storeTrack.size !== 0 ){
        savedPlayList = [...storeTrack].map(([key,data])=>{
            return <SongDetail key={key} trackDetail={data}  id={key} action={["remove", handleRemoveTrackFromStore]} />
        })
    }


    //Track Display List is generated by the Search result by mapping  

    return (
        <div className={styles.userDisplayContainer}>
            
            <div className={styles.inputWrapper}>
                <h1>Saved Playlist</h1>
                <span>Rename playlist as </span>
                <input type='text' className={styles.titleInput} value={listTitle} onChange={handlePlayListTitle} onClick={resetPlayListTitle} ></input>
            </div>

            <div className={styles.userListContainer}>
                {savedPlayList}
            </div>
            <div className={styles.exportButton}  onClick={handleLoginService} >
                <span>Login to </span>
                <img src={spotifyLogo} alt="Spotify Logo" />
            </div>
        </div>
    );
}); 

//Export Component 
export {UsertDisplayContainer}; 
