import React from'react';
import styles from './userDisplayList.module.css'
import { SongDetail } from '../trackDetail/songDetail';
import spotifyLogo from '../userListContainer/image/Spotify-Logo-Download-Free.png'; 

 const UsertDisplayContainer = React.memo((props)=>{

    //Variable 
    //Title Control 
    const listTitle= props.playListControl.listTitle.title; 
    const {handlePlayListTitle,resetPlayListTitle} = props.playListControl.listTitle.action;

    //List Button Control 
    const {instruction} = props.playListControl.button; 
    const buttonAction = props.playListControl.button.action; 

    //Store List Control 
    const {handleRemoveTrackFromStore} = props.storeActions; 
    const {storeTrack}= props;



    //Iterate the saved playlist
    let savedPlayList; 

    if(storeTrack.size !== 0 ){
        savedPlayList = [...storeTrack].map(([key,data])=>{
            return <SongDetail key={key} trackDetail={data}  id={key} action={["remove", handleRemoveTrackFromStore]} />
        })
    }


    //Track Display List is generated by the Search result by mapping  

    return (
        <div className={styles.userDisplayContainer}>
            
            <div className={styles.inputWrapper}>
                <h1>Saved Playlist</h1>
                <span>rename as </span>
                <input type='text' className={styles.titleInput} value={listTitle} onChange={handlePlayListTitle} onClick={resetPlayListTitle} ></input>
            </div>

            <div className={styles.userListContainer}>
                {savedPlayList}
            </div>
            
            <div className={styles.exportButton}  onClick={buttonAction} >
                <span>{instruction} </span>
                <img src={spotifyLogo} alt="Spotify Logo" />
            </div>
        </div>
    );
}); 

//Export Component 
export {UsertDisplayContainer}; 
