import userResultStyles from './userDisplayList.module.css'
import { SongDetailContainer } from '../SongDetailContainer/songDetailContainer';

export function UsertDisplayContainer(props) {


    function resetPlayListName() {
        props.setPlaylistName('');
    }

    function handleInputBox(event) {
        props.setPlaylistName(event.target.value);
    }

    function handleInputFocusOut(event) {
        if (!event.target.value) {
            props.setPlaylistName('New Playlist')
        }
    }



    //Track Display List is generated by the Search result by mapping  

    return (
        <div className={userResultStyles.userDisplayContainer}>
            <input type='text' className={userResultStyles.titleInput} value={props.playlistName} onChange={handleInputBox} onClick={resetPlayListName} onBlur={handleInputFocusOut}></input>

            <div className={userResultStyles.userListContainer}>
                {
                    props.playlistTracks.map((trackInfo) => {
                        const trackDetail = {
                            trackInfo,
                            action: {
                                setAction: props.setAction,
                                setpendingTrackInfo: props.setpendingTrackInfo,
                            },
                            button: "-"
                        };
                        return <SongDetailContainer key={trackInfo.trackID} trackDetail={trackDetail} />
                    }
                    )
                }
            </div>
            <input className={userResultStyles.exportButton} type='submit' value="Export to Spotify" onClick={props.handleExportBtn} ></input>
        </div>
    );
}

