import displayResultStyles from './resultDisplay.module.css'
import { SongDetailContainer } from '../SongDetailContainer/songDetailContainer';


export function DisplayContainer(props) {

    //Track Display List is generated by the Search result by mapping  
 
    return (
        <div className={displayResultStyles.resultDisplayContainer}>
            <h1>Result</h1>
            <div className={displayResultStyles.resultListContainer}>
                {
                   props.displayList.map((trackInfo)=>{
                        const trackDetail = {
                            trackInfo,
                            action :{
                                setAction: props.setAction,
                                setpendingTrackInfo: props.setpendingTrackInfo,
                            },
                            button: "+"
                        };
                        return <SongDetailContainer key={trackInfo.trackID} trackDetail={trackDetail}  />
                   })
                }
            </div>
        </div>
    );

}