import React, { useEffect, useState } from 'react';
import displayResultStyles from './resultDisplay.module.css'
import { SongDetailContainer } from '../SongDetailContainer/songDetailContainer';


export function DisplayContainer(props) {

    //Track Display List is generated by the Search result by mapping  
    let resultlistItems
    if (props.displayList.length != 0) {
        resultlistItems = props.displayList.map(
            (trackInfo) => {
                return <SongDetailContainer trackInfo={trackInfo} setAction={props.setAction} setpendingTrackInfo={props.setpendingTrackInfo} button="+" />
            }
        )
    }



    return (
        <div className={displayResultStyles.resultDisplayContainer}>
            <h1>Result</h1>
            <div className={displayResultStyles.resultListContainer}>
                {resultlistItems}
            </div>
        </div>
    );

}